#!/usr/bin/env php
<?php
use \silk\core\Application;
use \silk\cli\Cli;

//Find silk.api.php
//First look in lib dir
$api_file = '';
$rack_file = '';
if (file_exists(dirname(__FILE__) . '/lib/silk/silk.api.php'))
{
	$api_file = dirname(__FILE__) . '/lib/silk/silk.api.php';
	define('ROOT_DIR', dirname(__FILE__));
}
else if (file_exists(dirname(__FILE__) . '/silk.api.php')) //We're in the main dir
{
	$api_file = dirname(__FILE__) . '/silk.api.php';
	define('ROOT_DIR', dirname(__FILE__));
}
else //PEAR?
{
	if (include_once("PEAR/Config.php"))
	{
		$config = PEAR_Config::singleton('', '');
		$cmd = $config->get('php_dir');
		if ($cmd && !empty($cmd))
		{
			$potential_path = $cmd . '/silk/silk.api.php';
			if (file_exists($potential_path))
			{
				$api_file = $potential_path;
				$rack_dir = $cmd . '/silk/vendor/rack/lib';
			}

			if (isset($_SERVER['PWD']))
			{
				define('ROOT_DIR', $_SERVER['PWD']);
			}
			else
			{
				define('ROOT_DIR', dirname(__FILE__));
			}
		}
	}
}

if (!empty($api_file))
{
	include_once($api_file);
}
else
{
	fwrite(STDERR, "Can't find silk libraries.  Exiting.\n");
	exit(1);
}

Application::getInstance(array('run_init' => false))->setup();

require dirname($api_file) . '/vendor/phake/lib/runner.php';

$runner = new \phake\Runner('', true, array(SILK_LIB_DIR));
