#!/usr/bin/env php
<?php
use \silk\core\Application;
use \silk\cli\Cli;

//Find silk.api.php
//First look in lib dir
$api_file = '';
if (strpos('@php_bin@', '@php_bin') === 0)  // not a pear install
{
	if (file_exists(dirname(__FILE__) . '/lib/silk/silk.api.php'))
	{
		$api_file = dirname(__FILE__) . '/lib/silk/silk.api.php';
		define('ROOT_DIR', dirname(__FILE__));
	}
	else if (file_exists(dirname(__FILE__) . '/silk.api.php')) //We're in the main dir
	{
		$api_file = dirname(__FILE__) . '/silk.api.php';
		define('ROOT_DIR', dirname(__FILE__));
	}
}
else //PEAR, baby!
{
	$api_file = "@pear_directory@/silk/silk.api.php";
	if (isset($_SERVER['PWD']))
	{
		define('ROOT_DIR', $_SERVER['PWD']);
	}
	else
	{
		define('ROOT_DIR', "@pear_directory@/silk");
	}
}

if (!empty($api_file))
{
	include_once($api_file);
}
else
{
	fwrite(STDERR, "Can't find silk libraries.  Exiting.\n");
	exit(1);
}

$rack_dir = joinPath(SILK_LIB_DIR, 'vendor', 'rack', 'lib');
include_once(joinPath($rack_dir, 'Rack.php'));

Application::getInstance(array('run_init' => false))->setup();

require dirname($api_file) . '/vendor/phake/lib/runner.php';

$dirs = array(SILK_LIB_DIR);

$list_of_files = array('.htaccess', 'app', 'vendor', 'public');
foreach ($list_of_files as $one_file)
{
	if (is_dir($one_file) || is_file($one_file))
	{
		$dirs[] = ROOT_DIR;
		break;
	}
}

$runner = new \phake\Runner('', true, array_unique($dirs));
